# Generated by Django 4.0.6 on 2022-07-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_band_like_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='help',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
