# Generated by Django 4.0.6 on 2022-07-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='help',
        ),
    ]
